title:    Josh Levinson
url:      https://www.joshlevinson.xyz
baseurl:  ""

exclude:  ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

theme:    minimal-mistakes-jekyll
